{% set version = "0.2.0" %}

package:
  name: conda-content-trust
  version: {{ version }}

source:
  url: https://github.com/conda/conda-content-trust/archive/refs/tags/{{ version }}.tar.gz
  sha256: ded769f69a0491bd1e002ce949a332ae5a47a60ce733adb8a724802c8fdfe02b

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python
  entry_points:
    - conda-content-trust=conda_content_trust.cli:cli

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
    - wheel
  run:
    - python >=3.8
    - cryptography >=41

test:
  imports:
    - conda_content_trust
    - conda_content_trust.authentication
    - conda_content_trust.common
    - conda_content_trust.root_signing
    - conda_content_trust.signing
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-cov
    - securesystemslib  # extra dependency
  commands:
    - pip check
    - pytest -v tests
    - conda-content-trust --help

about:
  home: https://github.com/conda/conda-content-trust
  summary: Signing and verification tools for Conda
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/conda/conda-content-trust
  doc_url: https://github.com/conda/conda-content-trust/blob/main/README.md

extra:
  recipe-maintainers:
    - wolfv
    - adriendelsalle
    - awwad
    - chenghlee
    - kenodegard
