{% set version = "0.2.0" %}

package:
  name: conda-content-trust
  version: {{ version }}

source:
  url: https://github.com/conda/conda-content-trust/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4a2da41a62cd6307090038fc89cdffcf4ea92cfea505cd192dfdaa9f04408195

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  number: 0
  noarch: python
  entry_points:
    - conda-content-trust=conda_content_trust.cli:cli

requirements:
  host:
    - python >=3.5
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
    - wheel
  run:
    - python >=3.5
    - cryptography >=41

test:
  imports:
    - conda_content_trust
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - ruamel_yaml
  commands:
    - pip check
    - pytest -v tests
    - conda-content-trust --help

about:
  home: https://github.com/conda/conda-content-trust
  summary: Signing and verification tools for Conda
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/conda/conda-content-trust
  doc_url: https://github.com/conda/conda-content-trust/blob/main/README.md

extra:
  recipe-maintainers:
    - wolfv
    - adriendelsalle
    - awwad
    - chenghlee
    - kenodegard
